baseURL = 'http://kemokemo.github.io/kemokemo-blog/'
languageCode = 'ja-jp'
theme = "m10c"

title = 'KemoKemo Blog'

[params]
  author = 'kemokemo'
  description = 'KemoKemoの気ままなつぶやき'
  avatar = 'kemokemo-icon-s.png'
  menu_item_separator = " / "
  images = ['kemokemo-icon-s.png']
  favicon =  '/kemokemo-blog/favicon.png'
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/kemokemo"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/t2wonderland"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/kemokemo-blog/"
    weight = 1
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/kemokemo-blog/search/"
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/kemokemo-blog/tags/"

[params.style]
  primaryColor = "#37bcde"

# light style
#[params.style]
#  darkestColor = "#dfe2d4"
#  darkColor = "#fefeff"
#  lightColor = "#353b43"
#  lightestColor = "#242930"
#  primaryColor = "#22AAFF"
