baseURL = 'https://kemokemo.github.io/kemokemo-blog/'
languageCode = 'ja-jp'

[module]
[[module.imports]]
  path = 'github.com/kemokemo/hugo-theme-hello-friend'

[params]
  defaultTheme = "light"
  title = "KemoKemo Blog"
  subtitle = "きままなつぶやき"

  [params.logo]
    logoText = "KemoKemo Blog"
    logoHomeLink = "/kemokemo-blog"

