baseURL = 'http://kemokemo.github.io/kemokemo-blog/'
languageCode = 'ja-jp'
theme = "m10c"

title = 'KemoKemo Blog'

[params]
  author = 'kemokemo'
  description = 'KemoKemoの気ままなつぶやき'
  avatar = 'kemokemo-icon-s.png'
  menu_item_separator = " / "
  images = ['kemokemo-icon-s.png']
  favicon =  '/kemokemo-blog/favicon.png'
  enableTOC = true
  [[params.social]]
    icon = "github"
    name = "Github"
    url = "https://github.com/kemokemo"
  [[params.social]]
    icon = "twitter"
    name = "Twitter"
    url = "https://twitter.com/t2wonderland"
  [[params.social]]
    icon = "database"
    name = "Qiita"
    url = "https://qiita.com/KemoKemo"
  [[params.social]]
    icon = "book"
    name = "Blogger(旧ブログ)"
    url = "https://t2wonderland.blogspot.com/"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "search"
    name = "Search"
    url = "/search/"
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"

# dark style
#[params.style]
#  primaryColor = "#37bcde"

# lilac style
[params.style]
  darkestColor = "#a7adcdff"
  darkColor = "#e7ebf6ff"
  lightColor = "#353b43"
  lightestColor = "#242930"
  primaryColor = "#8d29a1ff"

[markup]
  [markup.tableOfContents]
    endLevel = 3
    ordered = true
    startLevel = 2