name: Build Hugo site

on:
  pull_request:
  workflow_call:
    inputs:
      upload-contents:
        description: 'If you upload the built contents to the pages, set true for this flag.'
        default: false
        required: true
        type: boolean

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      HUGO_VERSION: 0.148.2
    steps:
      - name: Install Hugo CLI
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb
          hugo version
      - name: Install Dart Sass Embedded
        run: sudo snap install dart-sass-embedded
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build with Hugo
        env:
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
        run: |
          hugo \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"
      - name: Setup Pages
        if: inputs.upload-contents
        id: pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        if: inputs.upload-contents
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public